### ISSUE TITLE
UX/DX tests and fixes

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-progress-bar#21]
Plan, book, conduct and report.

**Comment by tonygoldcrest** [comment]
[vaadin-progress-bar-dx.zip](https://github.com/vaadin/vaadin-progress-bar/files/1410719/vaadin-progress-bar-dx.zip)

**Comment by tomivirkki** [comment]
Task 1 is ok, Task 2 is a lot of work and in the end of the day, it tests the same thing as task 1 (setting the value property). Task 2 should instead test the min and max properties.

**Comment by tonygoldcrest** [comment]
https://gitlab.vaadin.com/elements/dx-tests/merge_requests/1
