### ISSUE TITLE
Progress bar with a label

### ISSUE THREAD

**Issue by tomasell** [vaadin/vaadin-progress-bar#32]
Hi there!
I think it's useful to have a progress bar with a label, what do you think about?
![number-progress-bar](https://user-images.githubusercontent.com/3263675/33436821-64f8c654-d5e6-11e7-9337-53fabfb57a82.jpg)

**Comment by jouni** [comment]
Yes, this use case has been “on the table” as a possible future feature addition. I’ve thought it could be provided as slotted content. For example, something like this:

```html
<vaadin-progress-bar value="[[value]]">
  <div>[[_formatValue(value)]]</div>
</vaadin-progress-bar>

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/vaadin-web-components/issues/158 which describes the same problem.
