### ISSUE TITLE
Indeterminate progress bar doesn’t work in Edge

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-progress-bar#36]
_From @jouni on November 15, 2017 14:28_

The colors are not applied, using custom properties and `var()`, for the `valo-progress-slide` keyframes.

_Copied from original issue: vaadin/vaadin-valo-styles#32_

**Comment by jouni** [comment]
Regression from 8aec886c5210a935a8372e67fb3eeb9f9731f0a7

**Comment by web-padawan** [comment]
Most likely related to: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12084341/

See also polymer/polymer@09897d1

@jouni we probably have to get rid of CSS custom properties here (it is the Edge once again, huh).

**Comment by platosha** [comment]
Seems to work fine for me on Edge 41 / EdgeHTML 16

![Screen Shot 2018-01-23 at 17.44.13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56499dd8360f9f1100b0cde4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f06b7191a379e80c2f55415e4dbe5d4a1f06a3a3dc78e2a436628f5a02be806f5973976e15aaed861db701ba24df46d6e0bd9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ef149e34f5da2153767f43b.png)

**Comment by jouni** [comment]
@platosha, that’s true, it seems to work fine in EdgeHTML 16. I probably tested this with EdgeHTML 14, where it occurs. That’s not a huge priority, so I’m closing this for now. Let’s see someone bumps into this.
