### ISSUE TITLE
Indeterminate mode of progress bar broken in Chrome

### ISSUE THREAD

**Issue by alump** [vaadin/vaadin-progress-bar#56]
https://vaadin.com/components/vaadin-progress-bar/java-examples

Indeterminate mode on our of Progress Bar seams to be broken on Chrome (at least on MacOS version of it, 75.0.3770.100). It doesn't isolate full width of progress bar, only partially (and which part seams to change).

Safari and Firefox does not have this issue on MacOS.

I attach issue as it's shows up on my 14 test app, but same issue happens also on demo page.

![Indeterminate](https://user-images.githubusercontent.com/1378660/60224733-95c7ca80-9838-11e9-8c60-c3c22d68b077.gif)

**Comment by web-padawan** [comment]
Confirmed. Appears to be a recent Chrome regression. 
Vivaldi on MacOS (based on Chrome/73.0.3683.88) does not have this issue.

**Comment by web-padawan** [comment]
Created the reduced test case: https://jsbin.com/zaduwas/edit?html,css,output
